"""
Unit tests for ap_create_master.config module.

Generated By: Cursor (Claude Sonnet 4.5)
"""

from ap_create_master import config


class TestConfig:
    """Tests for config constants."""

    def test_keyword_constants_defined(self):
        """Test that all keyword constants are defined."""
        assert config.NORMALIZED_HEADER_TYPE == "type"
        assert config.NORMALIZED_HEADER_CAMERA == "camera"
        assert config.NORMALIZED_HEADER_SETTEMP == "settemp"
        assert config.NORMALIZED_HEADER_GAIN == "gain"
        assert config.NORMALIZED_HEADER_OFFSET == "offset"
        assert config.NORMALIZED_HEADER_READOUTMODE == "readoutmode"
        assert config.NORMALIZED_HEADER_EXPOSURESECONDS == "exposureseconds"
        assert config.NORMALIZED_HEADER_DATE == "date"
        assert config.NORMALIZED_HEADER_FILTER == "filter"

    def test_required_keywords_structure(self):
        """Test that REQUIRED_KEYWORDS has correct structure."""
        assert "bias" in config.REQUIRED_KEYWORDS
        assert "dark" in config.REQUIRED_KEYWORDS
        assert "flat" in config.REQUIRED_KEYWORDS

        # Bias should not include exposureseconds
        assert (
            config.NORMALIZED_HEADER_EXPOSURESECONDS
            not in config.REQUIRED_KEYWORDS["bias"]
        )
        # Dark should include exposureseconds
        assert (
            config.NORMALIZED_HEADER_EXPOSURESECONDS in config.REQUIRED_KEYWORDS["dark"]
        )
        # Flat should include date and filter
        assert config.NORMALIZED_HEADER_DATE in config.REQUIRED_KEYWORDS["flat"]
        assert config.NORMALIZED_HEADER_FILTER in config.REQUIRED_KEYWORDS["flat"]

    def test_master_match_keywords(self):
        """Test that MASTER_MATCH_KEYWORDS excludes date and filter."""
        assert config.NORMALIZED_HEADER_DATE not in config.MASTER_MATCH_KEYWORDS
        assert config.NORMALIZED_HEADER_FILTER not in config.MASTER_MATCH_KEYWORDS
        assert config.NORMALIZED_HEADER_CAMERA in config.MASTER_MATCH_KEYWORDS

    def test_min_images_for_integration(self):
        """Test that MIN_IMAGES_FOR_INTEGRATION is defined and equals 3."""
        assert config.MIN_IMAGES_FOR_INTEGRATION == 3

    def test_image_type_constants(self):
        """Test that PixInsight image type constants are defined."""
        assert config.IMAGE_TYPE_BIAS == 1
        assert config.IMAGE_TYPE_DARK == 2
        assert config.IMAGE_TYPE_FLAT == 3
