"""
Unit tests for ap_create_master.grouping module.

Generated By: Cursor (Claude Sonnet 4.5)
"""

import pytest

from ap_create_master import config
from ap_create_master.grouping import (
    create_group_key,
    get_group_metadata,
    group_files,
)


class TestCreateGroupKey:
    """Tests for create_group_key function."""

    def test_bias_group_key(self):
        """Test creating group key for bias frames."""
        headers = {
            config.NORMALIZED_HEADER_TYPE: "bias",
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            config.NORMALIZED_HEADER_SETTEMP: "-10.00",
            config.NORMALIZED_HEADER_GAIN: "239",
            config.NORMALIZED_HEADER_OFFSET: "150",
            config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
        }
        key = create_group_key(headers, "bias")
        assert isinstance(key, tuple)
        assert len(key) == len(config.REQUIRED_KEYWORDS["bias"])
        assert key[0] == "bias"  # TYPE
        assert key[1] == "-10.00"  # SETTEMP
        assert key[4] == "ATR585M"  # CAMERA

    def test_dark_group_key(self):
        """Test creating group key for dark frames."""
        headers = {
            config.NORMALIZED_HEADER_TYPE: "dark",
            config.NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            config.NORMALIZED_HEADER_SETTEMP: "-10.00",
            config.NORMALIZED_HEADER_GAIN: "239",
            config.NORMALIZED_HEADER_OFFSET: "150",
            config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
        }
        key = create_group_key(headers, "dark")
        assert isinstance(key, tuple)
        assert len(key) == len(config.REQUIRED_KEYWORDS["dark"])
        assert key[0] == "dark"  # TYPE
        assert key[1] == "60.0"  # EXPOSURESECONDS

    def test_flat_group_key(self):
        """Test creating group key for flat frames."""
        headers = {
            config.NORMALIZED_HEADER_TYPE: "flat",
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            config.NORMALIZED_HEADER_SETTEMP: "-10.00",
            config.NORMALIZED_HEADER_GAIN: "239",
            config.NORMALIZED_HEADER_OFFSET: "150",
            config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
            config.NORMALIZED_HEADER_DATE: "2026-01-15",
            config.NORMALIZED_HEADER_FILTER: "B",
        }
        key = create_group_key(headers, "flat")
        assert isinstance(key, tuple)
        assert len(key) == len(config.REQUIRED_KEYWORDS["flat"])
        assert key[1] == "B"  # FILTER
        assert key[2] == "2026-01-15"  # DATE

    def test_missing_values_become_empty_string(self):
        """Test that missing header values become empty strings."""
        headers = {
            config.NORMALIZED_HEADER_TYPE: "bias",
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            # Missing other required keywords
        }
        key = create_group_key(headers, "bias")
        assert "" in key  # Missing values should be empty strings

    def test_unknown_frame_type_raises_error(self):
        """Test that unknown frame type raises ValueError."""
        with pytest.raises(ValueError, match="Unknown frame type"):
            create_group_key({}, "unknown")


class TestGroupFiles:
    """Tests for group_files function."""

    def test_group_files_by_key(self):
        """Test that files are grouped correctly."""
        files = [
            {
                "path": "file1.fits",
                "headers": {
                    config.NORMALIZED_HEADER_TYPE: "bias",
                    config.NORMALIZED_HEADER_CAMERA: "ATR585M",
                    config.NORMALIZED_HEADER_SETTEMP: "-10.00",
                    config.NORMALIZED_HEADER_GAIN: "239",
                    config.NORMALIZED_HEADER_OFFSET: "150",
                    config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
                },
            },
            {
                "path": "file2.fits",
                "headers": {
                    config.NORMALIZED_HEADER_TYPE: "bias",
                    config.NORMALIZED_HEADER_CAMERA: "ATR585M",
                    config.NORMALIZED_HEADER_SETTEMP: "-10.00",
                    config.NORMALIZED_HEADER_GAIN: "239",
                    config.NORMALIZED_HEADER_OFFSET: "150",
                    config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
                },
            },
            {
                "path": "file3.fits",
                "headers": {
                    config.NORMALIZED_HEADER_TYPE: "bias",
                    config.NORMALIZED_HEADER_CAMERA: "ATR585M",
                    config.NORMALIZED_HEADER_SETTEMP: "-9.00",  # Different temp
                    config.NORMALIZED_HEADER_GAIN: "239",
                    config.NORMALIZED_HEADER_OFFSET: "150",
                    config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
                },
            },
        ]
        groups = group_files(files, "bias")
        assert len(groups) == 2  # Two different groups
        # First group should have 2 files
        for group_key, group_files_list in groups.items():
            if len(group_files_list) == 2:
                assert group_files_list[0]["path"] in ["file1.fits", "file2.fits"]
                assert group_files_list[1]["path"] in ["file1.fits", "file2.fits"]
            else:
                assert len(group_files_list) == 1
                assert group_files_list[0]["path"] == "file3.fits"


class TestGetGroupMetadata:
    """Tests for get_group_metadata function."""

    def test_extract_metadata_for_bias(self):
        """Test extracting metadata for bias frames."""
        headers = {
            config.NORMALIZED_HEADER_TYPE: "bias",
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            config.NORMALIZED_HEADER_SETTEMP: "-10.00",
            config.NORMALIZED_HEADER_GAIN: "239",
            config.NORMALIZED_HEADER_OFFSET: "150",
            config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
        }
        metadata = get_group_metadata(headers, "bias")
        assert metadata[config.NORMALIZED_HEADER_TYPE] == "bias"
        assert metadata[config.NORMALIZED_HEADER_CAMERA] == "ATR585M"
        assert metadata[config.NORMALIZED_HEADER_SETTEMP] == "-10.00"

    def test_missing_values_not_included(self):
        """Test that missing header values are not included in metadata."""
        headers = {
            config.NORMALIZED_HEADER_TYPE: "bias",
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            # Missing other keywords
        }
        metadata = get_group_metadata(headers, "bias")
        assert config.NORMALIZED_HEADER_TYPE in metadata
        assert config.NORMALIZED_HEADER_CAMERA in metadata
        assert config.NORMALIZED_HEADER_SETTEMP not in metadata

    def test_unknown_frame_type_raises_error(self):
        """Test that unknown frame type raises ValueError."""
        with pytest.raises(ValueError, match="Unknown frame type"):
            get_group_metadata({}, "unknown")
