"""
Tests for CLI entry point (calibrate_masters.py main()).
Verifies argument parsing and main() integration.

Following CLI Testing Standards to prevent argparse attribute bugs.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

from ap_create_master.calibrate_masters import main, EXIT_SUCCESS, EXIT_ERROR


class TestMainCLI:
    """Tests for main() CLI entry point.

    Following CLI Testing Standards to verify argparse attribute mapping.
    Prevents runtime AttributeError from typos in args.attribute_name access.
    """

    def test_minimal_execution(self, tmp_path, mocker):
        """Test minimal required arguments (input_dir, output_dir)."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        # Mock generate_masters to isolate argparse logic
        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            ["ap-create-master", str(input_dir), str(output_dir), "--script-only"],
        )

        result = main()

        assert result == EXIT_SUCCESS
        # Verify generate_masters was called with correct positional args
        call_args = mock_generate.call_args
        assert call_args.args[0] == str(input_dir)  # input_dir
        assert call_args.args[1] == str(output_dir)  # output_dir

    def test_bias_master_dir_argument(self, tmp_path, mocker):
        """Test --bias-master-dir passes value correctly."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        bias_dir = tmp_path / "bias"
        input_dir.mkdir()
        output_dir.mkdir()
        bias_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
                "--bias-master-dir",
                str(bias_dir),
                "--script-only",
            ],
        )

        result = main()

        assert result == EXIT_SUCCESS
        call_args = mock_generate.call_args
        assert call_args.args[2] == str(bias_dir)  # bias_master_dir

    def test_dark_master_dir_argument(self, tmp_path, mocker):
        """Test --dark-master-dir passes value correctly."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        dark_dir = tmp_path / "dark"
        input_dir.mkdir()
        output_dir.mkdir()
        dark_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
                "--dark-master-dir",
                str(dark_dir),
                "--script-only",
            ],
        )

        result = main()

        assert result == EXIT_SUCCESS
        call_args = mock_generate.call_args
        assert call_args.args[3] == str(dark_dir)  # dark_master_dir

    def test_script_dir_argument(self, tmp_path, mocker):
        """Test --script-dir passes value correctly."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        script_dir = tmp_path / "scripts"
        input_dir.mkdir()
        output_dir.mkdir()
        script_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
                "--script-dir",
                str(script_dir),
                "--script-only",
            ],
        )

        result = main()

        assert result == EXIT_SUCCESS
        call_args = mock_generate.call_args
        assert call_args.args[4] == str(script_dir)  # script_dir

    def test_dryrun_flag(self, tmp_path, mocker):
        """Test --dryrun flag is correctly passed."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            ["ap-create-master", str(input_dir), str(output_dir), "--dryrun"],
        )

        result = main()

        assert result == EXIT_SUCCESS
        call_args = mock_generate.call_args
        assert call_args.kwargs["dryrun"] is True

    def test_debug_flag(self, tmp_path, mocker):
        """Test --debug flag is correctly passed."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
                "--debug",
                "--script-only",
            ],
        )

        result = main()

        assert result == EXIT_SUCCESS
        call_args = mock_generate.call_args
        assert call_args.kwargs["debug"] is True

    def test_quiet_flag(self, tmp_path, mocker):
        """Test --quiet flag is correctly passed."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
                "--quiet",
                "--script-only",
            ],
        )

        result = main()

        assert result == EXIT_SUCCESS
        call_args = mock_generate.call_args
        assert call_args.kwargs["quiet"] is True

    def test_quiet_short_flag(self, tmp_path, mocker):
        """Test -q (short form) flag works."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
                "-q",
                "--script-only",
            ],
        )

        result = main()

        assert result == EXIT_SUCCESS
        call_args = mock_generate.call_args
        assert call_args.kwargs["quiet"] is True

    def test_script_only_flag(self, tmp_path, mocker):
        """Test --script-only skips PixInsight execution."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([str(tmp_path / "script.js")], []),
        )
        mock_execute = mocker.patch("ap_create_master.calibrate_masters.run_pixinsight")

        mocker.patch(
            "sys.argv",
            ["ap-create-master", str(input_dir), str(output_dir), "--script-only"],
        )

        result = main()

        assert result == EXIT_SUCCESS
        mock_generate.assert_called_once()
        # PixInsight should not be executed with --script-only
        mock_execute.assert_not_called()

    def test_pixinsight_binary_required_without_script_only(self, tmp_path, mocker):
        """Test --pixinsight-binary is required when not using --script-only."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([str(tmp_path / "script.js")], []),
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
            ],  # No --script-only, no --pixinsight-binary
        )

        result = main()

        # Should return error because pixinsight-binary is missing
        assert result == EXIT_ERROR
        mock_generate.assert_called_once()

    def test_instance_id_argument(self, tmp_path, mocker):
        """Test --instance-id passes integer value correctly."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),  # No scripts, so execution is skipped
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
                "--instance-id",
                "456",
                "--script-only",
            ],
        )

        result = main()

        # Verify instance_id is parsed correctly (argparse type conversion)
        # The actual value isn't passed to generate_masters, but argparse validates it
        assert result == EXIT_SUCCESS
        mock_generate.assert_called_once()

    def test_multiple_flags_combined(self, tmp_path, mocker):
        """Test --dryrun --quiet --debug work together."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mock_generate = mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            return_value=([], []),
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-create-master",
                str(input_dir),
                str(output_dir),
                "--dryrun",
                "--quiet",
                "--debug",
            ],
        )

        result = main()

        assert result == EXIT_SUCCESS
        call_args = mock_generate.call_args
        assert call_args.kwargs["dryrun"] is True
        assert call_args.kwargs["quiet"] is True
        assert call_args.kwargs["debug"] is True

    def test_exception_returns_error_code(self, tmp_path, mocker):
        """Test EXIT_ERROR when generate_masters raises exception."""
        input_dir = tmp_path / "input"
        output_dir = tmp_path / "output"
        input_dir.mkdir()
        output_dir.mkdir()

        mocker.patch(
            "ap_create_master.calibrate_masters.generate_masters",
            side_effect=Exception("Test error"),
        )

        mocker.patch(
            "sys.argv",
            ["ap-create-master", str(input_dir), str(output_dir), "--script-only"],
        )

        result = main()

        assert result == EXIT_ERROR
