"""
Unit tests for ap_create_master.script_generator module.

Generated By: Cursor (Claude Sonnet 4.5)
"""

from unittest.mock import patch

import pytest

from ap_create_master import config
from ap_create_master.script_generator import (
    escape_js_string,
    generate_combined_script,
    generate_master_filename,
)


class TestEscapeJsString:
    """Tests for escape_js_string function."""

    def test_escapes_backslashes(self):
        """Test that backslashes are converted to forward slashes."""
        result = escape_js_string("C:\\path\\to\\file.fits")
        assert result == "C:/path/to/file.fits"

    def test_escapes_quotes(self):
        """Test that quotes are escaped."""
        result = escape_js_string('path with "quotes"')
        assert result == 'path with \\"quotes\\"'

    def test_handles_mixed_paths(self):
        """Test handling of mixed path separators and quotes."""
        result = escape_js_string('C:\\path\\with "quotes"\\file.fits')
        assert result == 'C:/path/with \\"quotes\\"/file.fits'


class TestGenerateMasterFilename:
    """Tests for generate_master_filename function."""

    @patch("ap_common.denormalize_header")
    def test_bias_filename(self, mock_denormalize):
        """Test generating filename for bias master."""
        mock_denormalize.side_effect = lambda k: {
            "camera": "INSTRUME",
            "settemp": "SET-TEMP",
            "gain": "GAIN",
            "offset": "OFFSET",
            "readoutmode": "READOUTM",
        }.get(k, k.upper())

        metadata = {
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            config.NORMALIZED_HEADER_SETTEMP: "-10.00",
            config.NORMALIZED_HEADER_GAIN: "239",
            config.NORMALIZED_HEADER_OFFSET: "150",
            config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
        }
        filename = generate_master_filename(metadata, "bias")
        assert filename.startswith("masterBias")
        assert "INSTRUME_ATR585M" in filename
        assert "SET-TEMP_-10.00" in filename

    @patch("ap_common.denormalize_header")
    def test_dark_filename_includes_exposure(self, mock_denormalize):
        """Test generating filename for dark master includes exposure."""
        mock_denormalize.side_effect = lambda k: {
            "exposureseconds": "EXPOSURE",
            "camera": "INSTRUME",
            "settemp": "SET-TEMP",
            "gain": "GAIN",
            "offset": "OFFSET",
            "readoutmode": "READOUTM",
        }.get(k, k.upper())

        metadata = {
            config.NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            config.NORMALIZED_HEADER_SETTEMP: "-10.00",
            config.NORMALIZED_HEADER_GAIN: "239",
            config.NORMALIZED_HEADER_OFFSET: "150",
            config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
        }
        filename = generate_master_filename(metadata, "dark")
        assert filename.startswith("masterDark")
        assert "EXPOSURE_60.0" in filename

    @patch("ap_common.denormalize_header")
    def test_flat_filename_includes_date_and_filter(self, mock_denormalize):
        """Test generating filename for flat master includes date and filter."""
        mock_denormalize.side_effect = lambda k: {
            "camera": "INSTRUME",
            "settemp": "SET-TEMP",
            "gain": "GAIN",
            "offset": "OFFSET",
            "readoutmode": "READOUTM",
            "date": "DATE-OBS",
            "filter": "FILTER",
        }.get(k, k.upper())

        metadata = {
            config.NORMALIZED_HEADER_CAMERA: "ATR585M",
            config.NORMALIZED_HEADER_SETTEMP: "-10.00",
            config.NORMALIZED_HEADER_GAIN: "239",
            config.NORMALIZED_HEADER_OFFSET: "150",
            config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
            config.NORMALIZED_HEADER_DATE: "2026-01-15",
            config.NORMALIZED_HEADER_FILTER: "B",
        }
        filename = generate_master_filename(metadata, "flat")
        assert filename.startswith("masterFlat")
        assert "DATE-OBS_2026-01-15" in filename
        assert "FILTER_B" in filename

    @patch("ap_common.denormalize_header")
    def test_sanitizes_invalid_chars(self, mock_denormalize):
        """Test that invalid filename characters are sanitized."""
        mock_denormalize.return_value = "TEST:KEY/with\\chars"

        metadata = {config.NORMALIZED_HEADER_CAMERA: "test:value/with\\chars"}
        filename = generate_master_filename(metadata, "bias")
        assert ":" not in filename
        assert "/" not in filename
        assert "\\" not in filename
        assert "-" in filename  # Should be replaced with dashes

    def test_unknown_frame_type_raises_error(self):
        """Test that unknown frame type raises ValueError."""
        with pytest.raises(ValueError, match="Unknown frame type"):
            generate_master_filename({}, "unknown")


class TestGenerateCombinedScript:
    """Tests for generate_combined_script function."""

    def test_generates_script_with_bias_groups(self, tmp_path):
        """Test generating script with bias groups."""
        output_dir = str(tmp_path / "output")
        bias_groups = [
            (
                {
                    config.NORMALIZED_HEADER_CAMERA: "ATR585M",
                    config.NORMALIZED_HEADER_SETTEMP: "-10.00",
                    config.NORMALIZED_HEADER_GAIN: "239",
                    config.NORMALIZED_HEADER_OFFSET: "150",
                    config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
                },
                ["file1.fits", "file2.fits"],
            )
        ]
        log_file = str(tmp_path / "test.log")
        script = generate_combined_script(output_dir, bias_groups, [], [], log_file)
        assert "Processing Bias Frames" in script
        assert "ImageIntegration" in script
        assert "file1.fits" in script or "file2.fits" in script
        assert "Console.beginLog" in script
        assert "Console.endLog" in script

    def test_generates_script_with_dark_groups(self, tmp_path):
        """Test generating script with dark groups."""
        output_dir = str(tmp_path / "output")
        dark_groups = [
            (
                {
                    config.NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                    config.NORMALIZED_HEADER_CAMERA: "ATR585M",
                    config.NORMALIZED_HEADER_SETTEMP: "-10.00",
                    config.NORMALIZED_HEADER_GAIN: "239",
                    config.NORMALIZED_HEADER_OFFSET: "150",
                    config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
                },
                ["dark1.fits", "dark2.fits"],
            )
        ]
        log_file = str(tmp_path / "test.log")
        script = generate_combined_script(output_dir, [], dark_groups, [], log_file)
        assert "Processing Dark Frames" in script
        assert "ImageIntegration" in script

    def test_generates_script_with_flat_groups(self, tmp_path):
        """Test generating script with flat groups."""
        output_dir = str(tmp_path / "output")
        flat_groups = [
            (
                {
                    config.NORMALIZED_HEADER_CAMERA: "ATR585M",
                    config.NORMALIZED_HEADER_SETTEMP: "-10.00",
                    config.NORMALIZED_HEADER_GAIN: "239",
                    config.NORMALIZED_HEADER_OFFSET: "150",
                    config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
                    config.NORMALIZED_HEADER_DATE: "2026-01-15",
                    config.NORMALIZED_HEADER_FILTER: "B",
                },
                ["flat1.fits", "flat2.fits"],
                "bias_master.xisf",
                "dark_master.xisf",
            )
        ]
        log_file = str(tmp_path / "test.log")
        script = generate_combined_script(output_dir, [], [], flat_groups, log_file)
        assert "Processing Flat Frames" in script
        assert "ImageCalibration" in script
        assert "ImageIntegration" in script
        assert "bias_master.xisf" in script
        assert "dark_master.xisf" in script

    def test_flat_without_masters_skips_calibration(self, tmp_path):
        """Test that flats without masters skip calibration phase."""
        output_dir = str(tmp_path / "output")
        flat_groups = [
            (
                {
                    config.NORMALIZED_HEADER_CAMERA: "ATR585M",
                    config.NORMALIZED_HEADER_SETTEMP: "-10.00",
                    config.NORMALIZED_HEADER_GAIN: "239",
                    config.NORMALIZED_HEADER_OFFSET: "150",
                    config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
                    config.NORMALIZED_HEADER_DATE: "2026-01-15",
                    config.NORMALIZED_HEADER_FILTER: "B",
                },
                ["flat1.fits", "flat2.fits"],
                None,  # No bias master
                None,  # No dark master
            )
        ]
        log_file = str(tmp_path / "test.log")
        script = generate_combined_script(output_dir, [], [], flat_groups, log_file)
        # Should not have calibration phase
        assert "ImageCalibration" not in script
        # But should have integration
        assert "ImageIntegration" in script

    def test_flat_calibrated_file_paths_generated(self, tmp_path):
        """Test that calibrated file paths are deterministically generated."""
        output_dir = str(tmp_path / "output")
        flat_groups = [
            (
                {
                    config.NORMALIZED_HEADER_CAMERA: "ATR585M",
                    config.NORMALIZED_HEADER_SETTEMP: "-10.00",
                    config.NORMALIZED_HEADER_GAIN: "239",
                    config.NORMALIZED_HEADER_OFFSET: "150",
                    config.NORMALIZED_HEADER_READOUTMODE: "Low Conversion Gain",
                    config.NORMALIZED_HEADER_DATE: "2026-01-15",
                    config.NORMALIZED_HEADER_FILTER: "B",
                },
                ["D:/input/flat1.fits", "D:/input/flat2.fits", "D:/input/flat3.fits"],
                "bias_master.xisf",
                "dark_master.xisf",
            )
        ]
        log_file = str(tmp_path / "test.log")
        script = generate_combined_script(output_dir, [], [], flat_groups, log_file)

        # Should contain calibrated file paths with _c.xisf suffix
        assert "flat1_c.xisf" in script
        assert "flat2_c.xisf" in script
        assert "flat3_c.xisf" in script

        # Should be in the calibrated directory
        assert "/calibrated/" in script

        # Should NOT use File.findFiles (that was the bug)
        assert "File.findFiles" not in script
        assert "FlagCaseInsensitive" not in script
