"""
Generated By: Cursor (Claude Sonnet 4.5)

Configuration for calibration master generation.

Defines required FITS keywords for grouping each frame type.
Uses normalized keyword names from ap-common normalization.
"""

# Import constants from ap-common
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_DATE,
    NORMALIZED_HEADER_FILTER,
    TYPE_BIAS,
    TYPE_DARK,
    TYPE_FLAT,
)

# Frame type list for processing
FRAME_TYPES = [TYPE_BIAS.lower(), TYPE_DARK.lower(), TYPE_FLAT.lower()]

# Required FITS keywords for grouping each frame type
# Keys are frame types (as found in TYPE keyword)
# Values are lists of normalized keyword names required for grouping
REQUIRED_KEYWORDS = {
    TYPE_BIAS.lower(): [
        NORMALIZED_HEADER_TYPE,
        NORMALIZED_HEADER_SETTEMP,
        NORMALIZED_HEADER_GAIN,
        NORMALIZED_HEADER_OFFSET,
        NORMALIZED_HEADER_CAMERA,
        NORMALIZED_HEADER_READOUTMODE,
    ],
    TYPE_DARK.lower(): [
        NORMALIZED_HEADER_TYPE,
        NORMALIZED_HEADER_EXPOSURESECONDS,
        NORMALIZED_HEADER_SETTEMP,
        NORMALIZED_HEADER_GAIN,
        NORMALIZED_HEADER_OFFSET,
        NORMALIZED_HEADER_CAMERA,
        NORMALIZED_HEADER_READOUTMODE,
    ],
    TYPE_FLAT.lower(): [
        NORMALIZED_HEADER_TYPE,
        NORMALIZED_HEADER_FILTER,
        NORMALIZED_HEADER_DATE,
        NORMALIZED_HEADER_SETTEMP,
        NORMALIZED_HEADER_GAIN,
        NORMALIZED_HEADER_OFFSET,
        NORMALIZED_HEADER_CAMERA,
        NORMALIZED_HEADER_READOUTMODE,
    ],
}

# Keywords used for matching bias/dark masters to flats
# These are the instrument settings that must match
# (excludes DATE and FILTER, which are flat-specific)
MASTER_MATCH_KEYWORDS = [
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_READOUTMODE,
]

# Frame types to ignore (e.g., lights)
IGNORED_TYPES = ["light"]

# PixInsight ImageIntegration imageType constants
IMAGE_TYPE_BIAS = 1
IMAGE_TYPE_DARK = 2
IMAGE_TYPE_FLAT = 3
